"use client";

import React from "react";
import { ForensicReport } from "@/types/report";
import {
  Printer,
  Download,
  ShieldAlert,
  FileCheck,
  CheckCircle2,
  Lock,
  Globe,
  Terminal
} from "lucide-react";
import { toast } from "sonner";

interface ReportPreviewProps {
  report: ForensicReport;
}

export function ReportPreview({ report }: ReportPreviewProps) {
  const handlePrint = () => {
    window.print();
  };

  const handleDownloadJson = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(report, null, 2));
    const downloadAnchor = document.createElement("a");
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `${report.reportNumber}_Forensic_Report.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
    toast.success("Downloaded raw report JSON");
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Top Action Controls Bar (Hidden during printing) */}
      <div className="p-4 rounded-xl bg-[#1a242f] border border-[#384959] flex items-center justify-between print:hidden">
        <div>
          <h3 className="text-xs font-bold text-white font-mono">
            Forensic Investigation Report • {report.reportNumber}
          </h3>
          <p className="text-[11px] text-[#6A89A7] font-mono">
            Generated by {report.generatedBy} on {new Date(report.generatedAt).toLocaleString()}
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleDownloadJson}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#243240] hover:bg-[#384959] text-xs font-mono text-[#BDDDFC] border border-[#384959] transition-colors"
          >
            <Download className="w-3.5 h-3.5 text-[#88BDF2]" />
            <span>JSON Export</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-[#88BDF2] hover:bg-[#BDDDFC] text-[#1a242f] font-bold text-xs font-mono transition-all shadow-glow"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print / Save PDF</span>
          </button>
        </div>
      </div>

      {/* Printable Report Document */}
      <div className="p-8 sm:p-12 rounded-2xl bg-[#1a242f] border border-[#384959] shadow-2xl text-slate-200 print:bg-white print:text-black print:border-none print:shadow-none print:p-0 space-y-8">
        {/* Document Header */}
        <div className="flex items-start justify-between border-b border-[#384959] print:border-gray-300 pb-6">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xl font-black tracking-wider text-white print:text-black">
                SENTINEL AI SOC
              </span>
              <span className="px-2 py-0.5 rounded bg-[#88BDF2]/20 text-[#BDDDFC] print:text-black text-xs font-mono font-bold">
                INCIDENT RESPONSE
              </span>
            </div>
            <h1 className="text-lg font-bold text-slate-100 print:text-black mt-2">
              {report.title}
            </h1>
            <p className="text-xs text-[#6A89A7] print:text-gray-600 font-mono mt-0.5">
              Report Ref: {report.reportNumber} • Classification: {report.classification.toUpperCase()}
            </p>
          </div>

          <div className="text-right font-mono text-xs">
            <div className="px-3 py-1 rounded bg-rose-500/20 text-rose-400 print:text-red-700 font-bold border border-rose-500/30 print:border-red-300 inline-block">
              RISK: {report.riskScore}/100 ({report.severity.toUpperCase()})
            </div>
            <div className="text-[11px] text-[#6A89A7] print:text-gray-500 mt-1">
              Confidence: {Math.round(report.confidence * 100)}%
            </div>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="space-y-2">
          <h2 className="text-xs font-mono uppercase font-bold text-[#88BDF2] print:text-gray-800 tracking-wider">
            1. Executive Summary & Incident Overview
          </h2>
          <p className="text-xs leading-relaxed text-slate-300 print:text-gray-700 font-sans">
            {report.executiveSummary}
          </p>
        </div>

        {/* Threat Assessment & Attribution */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <h2 className="text-xs font-mono uppercase font-bold text-[#88BDF2] print:text-gray-800 tracking-wider">
              2. Technical Threat Assessment
            </h2>
            <p className="text-xs leading-relaxed text-slate-300 print:text-gray-700 font-sans">
              {report.threatAssessment}
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xs font-mono uppercase font-bold text-[#88BDF2] print:text-gray-800 tracking-wider">
              3. Geolocation & Origin Attribution
            </h2>
            <p className="text-xs leading-relaxed text-slate-300 print:text-gray-700 font-sans">
              {report.originAttribution}
            </p>
          </div>
        </div>

        {/* Evidence & Protocol Matrix */}
        <div className="space-y-3">
          <h2 className="text-xs font-mono uppercase font-bold text-[#88BDF2] print:text-gray-800 tracking-wider">
            4. Cryptographic Authentication Findings
          </h2>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono text-xs">
            <div className="p-3 rounded-lg bg-[#243240] print:bg-gray-100 border border-[#384959] print:border-gray-300">
              <span className="text-[10px] text-[#6A89A7] print:text-gray-500 uppercase">SPF Status</span>
              <div className="font-bold text-white print:text-black mt-1">
                {report.evidenceSummary.spfStatus}
              </div>
            </div>
            <div className="p-3 rounded-lg bg-[#243240] print:bg-gray-100 border border-[#384959] print:border-gray-300">
              <span className="text-[10px] text-[#6A89A7] print:text-gray-500 uppercase">DKIM Status</span>
              <div className="font-bold text-white print:text-black mt-1">
                {report.evidenceSummary.dkimStatus}
              </div>
            </div>
            <div className="p-3 rounded-lg bg-[#243240] print:bg-gray-100 border border-[#384959] print:border-gray-300">
              <span className="text-[10px] text-[#6A89A7] print:text-gray-500 uppercase">DMARC Status</span>
              <div className="font-bold text-white print:text-black mt-1">
                {report.evidenceSummary.dmarcStatus}
              </div>
            </div>
            <div className="p-3 rounded-lg bg-[#243240] print:bg-gray-100 border border-[#384959] print:border-gray-300">
              <span className="text-[10px] text-[#6A89A7] print:text-gray-500 uppercase">Origin Node</span>
              <div className="font-bold text-white print:text-black mt-1">
                {report.evidenceSummary.originIp}
              </div>
            </div>
          </div>
        </div>

        {/* IOC Appendix Table */}
        <div className="space-y-3">
          <h2 className="text-xs font-mono uppercase font-bold text-[#88BDF2] print:text-gray-800 tracking-wider">
            5. IOC Observables Appendix ({report.iocs.length} Indicators)
          </h2>
          <div className="overflow-x-auto rounded-lg border border-[#384959] print:border-gray-300">
            <table className="w-full text-left text-xs font-mono">
              <thead className="bg-[#243240] print:bg-gray-100 text-[10px] text-[#6A89A7] print:text-gray-600 uppercase">
                <tr>
                  <th className="py-2 px-3">Type</th>
                  <th className="py-2 px-3">Indicator Value</th>
                  <th className="py-2 px-3">Severity</th>
                  <th className="py-2 px-3">Category</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#384959] print:divide-gray-200">
                {report.iocs.map((ioc, idx) => (
                  <tr key={idx}>
                    <td className="py-2 px-3 font-bold">{ioc.type}</td>
                    <td className="py-2 px-3 text-[#BDDDFC] print:text-blue-800 break-all">{ioc.value}</td>
                    <td className="py-2 px-3 font-bold text-rose-400 print:text-red-700">{ioc.severity}</td>
                    <td className="py-2 px-3 text-[#6A89A7] print:text-gray-600">{ioc.category}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Remediation Action Steps */}
        <div className="space-y-2">
          <h2 className="text-xs font-mono uppercase font-bold text-[#88BDF2] print:text-gray-800 tracking-wider">
            6. Prescribed Remediation & Containment Plan
          </h2>
          <ul className="list-disc pl-5 space-y-1 text-xs text-slate-300 print:text-gray-700 font-sans">
            {report.remediationSteps.map((step, idx) => (
              <li key={idx}>{step}</li>
            ))}
          </ul>
        </div>

        {/* Chain of Custody Sign-Off */}
        <div className="pt-6 border-t border-[#384959] print:border-gray-300 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 font-mono text-[11px]">
          <div>
            <div className="text-[#6A89A7] print:text-gray-500">Forensic Custodian Signature:</div>
            <div className="font-bold text-white print:text-black mt-0.5">{report.chainOfCustody.custodian}</div>
          </div>

          <div className="text-right">
            <div className="text-[#6A89A7] print:text-gray-500">SHA-256 Vault Verification:</div>
            <div className="font-bold text-emerald-400 print:text-green-700 mt-0.5">
              {report.chainOfCustody.sha256Verification} ({report.chainOfCustody.immutableLedgerRef})
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
